name: pipeline
on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: configure runner
        run: |
          sudo apt-get install sshpass
          sudo apt-get update
          java -version
          sudo apt install default-jre
          java -version
          sudo apt update
          sudo apt install maven
          mvn -version
      - name: checkout
        uses: actions/checkout@v4
      - name: mvn install
        run: | 
          mvn install clean package
      - name: Check for Dockerfile
        id: Dockerfile_check
        run: |
          if test -f "Dockerfile"; then
          echo "check_result=true" >> $GITHUB_OUTPUT
          else
          echo "check_result=false" >> $GITHUB_OUTPUT
          fi
      - name: Run dependent step
        if: steps.Dockerfile_check.outputs.check_result == 'true'
        run: |
         echo Docker build
      - name: push image
        run: echo push image to registry
      - name: scp artifact
        run: | 
          echo $GITHUB_REF | cut -f3 -d/
      - name: deploy
        run: | 
          echo 'call deploy'
  
        
  
  
