name: pipeline
on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_REF
        run: echo $GITHUB_REF | cut -f3 -d/
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        run: | 
          sudo apt-get update
          java -version
          sudo apt install default-jre
          java -version
          sudo apt update
          sudo apt install maven
          mvn -version
      - name: mvn install
        run: | 
          mvn install clean package
      - name: scp artifact
        run: | 
          ls -ltr target
  
        
  
  
