name: pipeline
on: 
  workflow_dispatch

jobs:
  pipeline:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        run: | 
          apt-get update
          apt-install java
          apt-install maven
        
  
  
