name: pipeline
on: 
  workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install java
        run: | 
          sudo apt-get update
          java -version
          sudo apt install default-jre
          java -version
          sudo apt install maven
          maven -version
          
        
  
  
